<?php

namespace AppBundle\Repository;

/**
 * BlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogRepository extends BaseRepository
{
    public function getLastArticles($id)
    {
        $query = $this->createQueryBuilder('a')
            ->where('a.id < :id')
            ->setParameter('id', $id)
            ->setMaxResults(4)
            ->orderBy('a.date','DESC')
            ->getQuery();

        return $query->getResult();
    }
}
