<?php

namespace AppBundle\Repository;

/**
 * LovestoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LovestoryRepository extends BaseRepository
{
}