<?php

namespace AppBundle\Repository;

/**
 * rsvpRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class rsvpRepository extends \Doctrine\ORM\EntityRepository
{
}
