<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findMarried()
    {
        $query = $this->createQueryBuilder('u')
            ->where('u.role = :role')
            ->setParameter('role', 1)
            ->getQuery();

        return $query->getResult();
    }
}
