<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends BaseRepository
{
    public function findMarried()
    {
        $query = $this->createQueryBuilder('u')
            ->join('u.role', 'r')
            ->where('r.role = :groom')
            ->orWhere('r.role = :bride')
            ->setParameter('groom', 'groom')
            ->setParameter('bride', 'bride')
            ->getQuery();

        return $query->getResult();
    }
}
