<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends BaseRepository
{
    public function findMarried()
    {
        $query = $this->createQueryBuilder('u')
            ->join('u.role', 'r')
            ->where('r.role = :groom')
            ->orWhere('r.role = :bride')
            ->setParameter('groom', 'groom')
            ->setParameter('bride', 'bride')
            ->getQuery();

        return $query->getResult();
    }

    public function findImportantPeople()
    {
        $query = $this->createQueryBuilder('u')
            ->join('u.role', 'r')
            ->where('r.role != :groom')
            ->AndWhere('r.role != :bride')
            ->AndWhere('r.role != :pasteur')
            ->setParameter('groom', 'groom')
            ->setParameter('bride', 'bride')
            ->setParameter('pasteur', 'Pasteur')
            ->getQuery();

        return $query->getResult();
    }

    public function findGromm()
    {
        $query = $this->createQueryBuilder('u')
            ->join('u.role', 'r')
            ->where('r.role = :groom')
            ->setParameter('groom', 'groom')
            ->getQuery();

        return $query->getSingleResult();
    }

    public function findPastor()
    {
        $query = $this->createQueryBuilder('u')
            ->join('u.role', 'r')
            ->where('r.role = :pasteur')
            ->setParameter('pasteur', 'Pasteur')
            ->getQuery();

        return $query->getResult();
    }
}
