<?php

namespace AppBundle\Repository;

/**
 * WebsiteTextRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WebsiteTextRepository extends BaseRepository
{
}
