<?php
/**
 * Created by PhpStorm.
 * User: Samuel
 * Date: 16-06-22
 * Time: 7:07 PM
 */

namespace AppBundle\Manager;


use AppBundle\Entity\Comment;
use Doctrine\ORM\EntityManager;
use Symfony\Component\HttpKernel\Kernel;

class BlogManager extends BaseManager
{
    public function __construct(EntityManager $em, Kernel $kernel, $className)
    {
        parent::__construct($em, $kernel, $className);
    }

    public function save($data)
    {
        if ($data->getDate() == null) {
            $data->setDate(new \DateTime());
        }
        parent::save($data); // TODO: Change the autogenerated stub
    }

    /**
     * Get random article
     */
    public function getRandomArticle()
    {
        $results = array();
        $articles = $this->em->getRepository('AppBundle:Blog')->findAll();
        shuffle($articles);
        for ($i = 0; $i < 3; $i++) {
            $results[] = $articles[$i];
        }
        return $results;
    }
}